// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	rooms "cozy-inn/businesses/rooms"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: roomDomain
func (_m *Repository) Create(roomDomain rooms.Domain) error {
	ret := _m.Called(roomDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(rooms.Domain) error); ok {
		r0 = rf(roomDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: roomType
func (_m *Repository) Delete(roomType string) error {
	ret := _m.Called(roomType)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(roomType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllRoom provides a mock function with given fields:
func (_m *Repository) GetAllRoom() ([]rooms.Domain, error) {
	ret := _m.Called()

	var r0 []rooms.Domain
	if rf, ok := ret.Get(0).(func() []rooms.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rooms.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomByType provides a mock function with given fields: roomType
func (_m *Repository) GetRoomByType(roomType string) (rooms.Domain, error) {
	ret := _m.Called(roomType)

	var r0 rooms.Domain
	if rf, ok := ret.Get(0).(func(string) rooms.Domain); ok {
		r0 = rf(roomType)
	} else {
		r0 = ret.Get(0).(rooms.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(roomType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: roomDomain
func (_m *Repository) Update(roomDomain rooms.Domain) error {
	ret := _m.Called(roomDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(rooms.Domain) error); ok {
		r0 = rf(roomDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
