
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Unit Testing Use Case
      run: go clean -testcache;  go test ./businesses/... -v
    - name: Stopping old docker container
      run: sudo docker stop /cozy-innn || true
    - name: Removing old docker container
      run: sudo docker rm /cozy-inn || true
    - name: Build docker images
      run: docker build -t cozy-inn:1.0.0 .
    - name: Run docker
      run: docker run -it -e GOOGLE_APPLICATION_CREDENTIALS='/app/.firebase/service-account.json' -v /home/ubuntu/service-account.json:/app/.firebase/service-account.json -v /home/ubuntu/.env:/app/.env --name cozy-inn -p 3000:3000 cozy-inn:1.0.0
